### ISSUE TITLE
Error in running rcnn object detector

### ISSUE THREAD

**Issue by tvkpz** [rayglover-ibm/serving-caffe#7]
I tried to follow the steps to run the rccn object detector. But the client call exists with the following error.

~/serving-caffe# bazel-bin/tensorflow_serving/example/obj_detector_client --server=localhost:9000 \
>     --imgdir=/tmp/images --num_tests=10 --concurrency=2
Connected. Input Shape: (3, 800, 600)
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "/root/serving-caffe/bazel-bin/tensorflow_serving/example/obj_detector_client.runfiles/tf_serving/tensorflow_serving/example/obj_detector_client.py", line 228, in <module>
    tf.app.run()
  File "/root/serving-caffe/bazel-bin/tensorflow_serving/example/obj_detector_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/serving-caffe/bazel-bin/tensorflow_serving/example/obj_detector_client.runfiles/tf_serving/tensorflow_serving/example/obj_detector_client.py", line 214, in main
    stats, results = do_inference(stub, FLAGS.concurrency, n, ims)
  File "/root/serving-caffe/bazel-bin/tensorflow_serving/example/obj_detector_client.runfiles/tf_serving/tensorflow_serving/example/obj_detector_client.py", line 140, in do_inference
    im_input = im_transpose(im)
  File "/root/serving-caffe/bazel-bin/tensorflow_serving/example/obj_detector_client.runfiles/tf_serving/tensorflow_serving/example/obj_detector_client.py", line 86, in im_transpose
    R, G, B = im.transpose((2, 0, 1))
ValueError: too many values to unpack
An RPC error occured: CancellationError(code=StatusCode.CANCELLED, details="Cancelled")

Appreciate any help in solving this .

**Comment by rayglover-ibm** [comment]
Looks like the error occurs when transposing an input image (which is just a numpy array). The image must be RGB for this example. Perhaps yours isn't?

**Comment by tvkpz** [comment]
Thanks for replying. Actually when I start the server its keeps printing a lot of statements on screen 

-------- Code trace -----------------

2017-08-04 06:17:50: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:51: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:51: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:52: I tensorflow_serving/servables/caffe/caffe_serving_session.cc:155] Caffe execution mode: GPU (device id: 0)
2017-08-04 06:17:52: I tensorflow_serving/servables/caffe/caffe_serving_session.cc:201] Loaded Network:
  name: VGG_ILSVRC_16_layers
  inputs: 2
  outputs: 2
  initial batch-size: 1
  output classes: Tensor<type: string shape: [1,21] values: __background__ aeroplane bicycle...>
2017-08-04 06:17:52: I tensorflow_serving/servables/caffe/caffe_session_bundle.cc:107] Running restore op for CaffeSessionBundle
2017-08-04 06:17:52: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:52: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:53: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:53: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:54: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:54: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:55: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:55: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:56: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:56: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
[libprotobuf WARNING external/protobuf/src/google/protobuf/io/coded_stream.cc:605] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING external/protobuf/src/google/protobuf/io/coded_stream.cc:82] The total number of bytes read was 548317115
2017-08-04 06:17:57: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:57: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:58: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:58: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:17:59: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:17:59: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:18:00: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:18:00: I tensorflow_serving/example/obj_detector.cc:514] Waiting for models to be loaded...
2017-08-04 06:18:01: I tensorflow_serving/servables/caffe/caffe_session_bundle.cc:146] Done loading SessionBundle
2017-08-04 06:18:01: I tensorflow_serving/core/loader_harness.cc:122] Successfully loaded servable version {name: default version: 1}
2017-08-04 06:18:01: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:18:01: I tensorflow_serving/example/obj_detector.cc:414] Running...
2017-08-04 06:18:02: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1
2017-08-04 06:18:03: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: default version: 1}; Servable path: /tmp/obj_detector/00000001; Polling frequency: 1

------------------------------------
After sometime I get MemoryDump issues.

---------ps -ef results -------------- 
root      21183 119214  7 06:17 ?        00:00:13 ./bazel-bin/tensorflow_serving/example/obj_detector --port=9
root     119399      0 26 05:54 ?        00:07:01 bazel(root) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath

----- Question ----------

Do you have any idea what is wrong?

------------


As an alternative:
I used a tensorflow implementation of faster rcnn to get a checkpoint file. (https://github.com/endernewton/tf-faster-rcnn)
Can you give some pointers into how I can make TFS work for that. I face issues with all the extra python code that come with the tensorflow faster-rcnn implementation.

Also
I am trying to understand how you made caffe to work with Tensorflow serving as an example of custom models like scikit-learn to work with TFS. Any ideas where to start?

Thanks!

**Comment by rayglover-ibm** [comment]
Very difficult to see what could be wrong without a stack trace within the core dump. You could use gdb to do this.

As for making scikit-learn 'just work' with TFS, it would be both hard and complex. You would have to be an expert at embedding Python in multi-threaded c++ applications.
